export const Performers = [
  {
    email: 'martin@gmail.com',
    password: '1234566',
    name: 'Martin Tourret',
    category: 'Singer',
    genre: 'pop music',
    cost_per_hour: 230,
    profile_pic_url:
      'https://media-exp1.licdn.com/dms/image/C5603AQEVQ6n3joIo2g/profile-displayphoto-shrink_800_800/0/1572341491806?e=1613606400&v=beta&t=yW7NoJxV44vqj7MOMNJmiH-dlbFIKcgJjbYMgeIfImQ',
  },
  {
    email: 'bruno@gmail.com',
    password: '1234566',
    name: 'Bruno Adami',
    category: 'Singer',
    genre: 'rock and roll',
    cost_per_hour: 300,
    profile_pic_url:
      'https://media-exp1.licdn.com/dms/image/C4D03AQGMUGiMPWNa-g/profile-displayphoto-shrink_200_200/0/1595956658196?e=1613606400&v=beta&t=DNZQMANyQ_SadBJmFPmx3Fr7e570UgpYgxVsIQe8ArY',
  },
  {
    email: 'aline@gmail.com',
    password: '1234566',
    name: 'Aline Fecher',
    category: 'Singer',
    genre: 'pop music',
    cost_per_hour: 250,
    profile_pic_url: 'https://www.metromodels.com/images/board/talent/2.jpg',
  },
  {
    email: 'arelis@gmail.com',
    password: '1234566',
    name: 'Arelis Sosa',
    category: 'Singer',
    genre: 'latin pop',
    cost_per_hour: 310,
    profile_pic_url: 'https://atlantablackstar.com/wp-content/uploads/2013/09/Arlenis-Sosa-Pe%C3%B1a-2.jpg',
  },
  {
    email: 'martin@gmail.com',
    password: '1234566',
    name: 'Martin Tourret',
    category: 'Singer',
    genre: 'pop music',
    cost_per_hour: 230,
    profile_pic_url:
      'https://media-exp1.licdn.com/dms/image/C5603AQEVQ6n3joIo2g/profile-displayphoto-shrink_800_800/0/1572341491806?e=1613606400&v=beta&t=yW7NoJxV44vqj7MOMNJmiH-dlbFIKcgJjbYMgeIfImQ',
  },
  {
    email: 'bruno@gmail.com',
    password: '1234566',
    name: 'Bruno Adami',
    category: 'Singer',
    genre: 'rock and roll',
    cost_per_hour: 300,
    profile_pic_url:
      'https://media-exp1.licdn.com/dms/image/C4D03AQGMUGiMPWNa-g/profile-displayphoto-shrink_200_200/0/1595956658196?e=1613606400&v=beta&t=DNZQMANyQ_SadBJmFPmx3Fr7e570UgpYgxVsIQe8ArY',
  },
  {
    email: 'aline@gmail.com',
    password: '1234566',
    name: 'Aline Fecher',
    category: 'Singer',
    genre: 'pop music',
    cost_per_hour: 250,
    profile_pic_url: 'https://www.metromodels.com/images/board/talent/2.jpg',
  },
  {
    email: 'arelis@gmail.com',
    password: '1234566',
    name: 'Arelis Sosa',
    category: 'Singer',
    genre: 'latin pop',
    cost_per_hour: 310,
    profile_pic_url: 'https://atlantablackstar.com/wp-content/uploads/2013/09/Arlenis-Sosa-Pe%C3%B1a-2.jpg',
  },
  {
    email: 'martin@gmail.com',
    password: '1234566',
    name: 'Martin Tourret',
    category: 'Singer',
    genre: 'pop music',
    cost_per_hour: 230,
    profile_pic_url:
      'https://media-exp1.licdn.com/dms/image/C5603AQEVQ6n3joIo2g/profile-displayphoto-shrink_800_800/0/1572341491806?e=1613606400&v=beta&t=yW7NoJxV44vqj7MOMNJmiH-dlbFIKcgJjbYMgeIfImQ',
  },
  {
    email: 'bruno@gmail.com',
    password: '1234566',
    name: 'Bruno Adami',
    category: 'Singer',
    genre: 'rock and roll',
    cost_per_hour: 300,
    profile_pic_url:
      'https://media-exp1.licdn.com/dms/image/C4D03AQGMUGiMPWNa-g/profile-displayphoto-shrink_200_200/0/1595956658196?e=1613606400&v=beta&t=DNZQMANyQ_SadBJmFPmx3Fr7e570UgpYgxVsIQe8ArY',
  },
  {
    email: 'aline@gmail.com',
    password: '1234566',
    name: 'Aline Fecher',
    category: 'Singer',
    genre: 'pop music',
    cost_per_hour: 250,
    profile_pic_url: 'https://www.metromodels.com/images/board/talent/2.jpg',
  },
  {
    email: 'arelis@gmail.com',
    password: '1234566',
    name: 'Arelis Sosa',
    category: 'Singer',
    genre: 'latin pop',
    cost_per_hour: 310,
    profile_pic_url: 'https://atlantablackstar.com/wp-content/uploads/2013/09/Arlenis-Sosa-Pe%C3%B1a-2.jpg',
  },
  {
    email: 'martin@gmail.com',
    password: '1234566',
    name: 'Martin Tourret',
    category: 'Singer',
    genre: 'pop music',
    cost_per_hour: 230,
    profile_pic_url:
      'https://media-exp1.licdn.com/dms/image/C5603AQEVQ6n3joIo2g/profile-displayphoto-shrink_800_800/0/1572341491806?e=1613606400&v=beta&t=yW7NoJxV44vqj7MOMNJmiH-dlbFIKcgJjbYMgeIfImQ',
  },
  {
    email: 'bruno@gmail.com',
    password: '1234566',
    name: 'Bruno Adami',
    category: 'Singer',
    genre: 'rock and roll',
    cost_per_hour: 300,
    profile_pic_url:
      'https://media-exp1.licdn.com/dms/image/C4D03AQGMUGiMPWNa-g/profile-displayphoto-shrink_200_200/0/1595956658196?e=1613606400&v=beta&t=DNZQMANyQ_SadBJmFPmx3Fr7e570UgpYgxVsIQe8ArY',
  },
  {
    email: 'aline@gmail.com',
    password: '1234566',
    name: 'Aline Fecher',
    category: 'Singer',
    genre: 'pop music',
    cost_per_hour: 250,
    profile_pic_url: 'https://www.metromodels.com/images/board/talent/2.jpg',
  },
  {
    email: 'arelis@gmail.com',
    password: '1234566',
    name: 'Arelis Sosa',
    category: 'Singer',
    genre: 'latin pop',
    cost_per_hour: 310,
    profile_pic_url: 'https://atlantablackstar.com/wp-content/uploads/2013/09/Arlenis-Sosa-Pe%C3%B1a-2.jpg',
  },
];

export const OFFERS = [
  {
    title: 'The best event',
    startTime: '27 june 12h AM',
    duration: '6h',
    status: 'accepted',
  },
  {
    title: 'The best event',
    startTime: '27 june 12h AM',
    duration: '6h',
    status: 'rejected',
  },
  {
    title: 'The best event',
    startTime: '27 june 12h AM',
    duration: '6h',
    status: 'waiting',
  },
  {
    title: 'The best event',
    startTime: '27 june 12h AM',
    duration: '6h',
    status: 'waiting',
  },
  {
    title: 'The best event',
    startTime: '27 june 12h AM',
    duration: '6h',
    status: 'rejected',
  },
  {
    title: 'The best event',
    startTime: '27 june 12h AM',
    duration: '6h',
    status: 'accepted',
  },
];
